= Payara Documentation UI
// Settings:
:experimental:
:hide-uri-scheme:
// Project URLs:
:url-project: https://gitlab.com/antora/antora-ui-default
:url-preview: https://antora.gitlab.io/antora-ui-default
:url-ci-pipelines: {url-project}/pipelines
:img-ci-status: {url-project}/badges/master/pipeline.svg
// External URLs:
:url-antora: https://antora.org
:url-payara-docs: https://docs.payara.fish
:url-antora-docs: https://docs.antora.org
:url-git: https://git-scm.com
:url-git-dl: {url-git}/downloads
:url-gulp: http://gulpjs.com
:url-opendevise: https://opendevise.com
:url-nodejs: https://nodejs.org
:url-nvm: https://github.com/creationix/nvm
:url-nvm-install: {url-nvm}#installation
:url-source-maps: https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map

This project is the source code and also a repository for the UI bundle that is used by {url-antora}[Antora] for both Payara Documentation editions to generate the {url-payara-docs}[Payara Platform and Cloud Documentation site].

The UI is based on the {url-project}[default Antora UI] and https://github.com/payara/pattern-library[Payara Blinky Pattern Library].

== Configuration Attributes

The UI has been customized to render and configure some elements based on the edition of the site being generated (whether for Payara Enterprise/Community or Payara Cloud). To this effect the following https://docs.antora.org/antora/latest/page/page-attributes/#custom-attribute[page attributes] are used:

`page-site-edition`::
The edition that corresponds to the documentation site.
One of:
* `enterprise`
* `community`
* `cloud`
* `qube`

== Theme Changes

This theme now uses Blinky for all HTML and CSS, the JS is a mix of Blinky for component interaction and the original Antora theme JS for generating menu states, jumping to positions on the page, and generating the TOCs. The original JS as some changes to work with the altered HTML structure. Please note that the icons will not be visible if you view the pages by simply dragging them into a browser window, they must be loaded from a server.

== Additions to Taskrunners

A couple of extra Gulp scripts have been added to copy the Blinky UI files needed that run along with the default theme scripts so you do not need to do anything extra. The new script files are:

* `gulp.d/blinky.js` - copies UI files into the public folder
* `gulp.d/blinkyJS.js` - copies and minifies UI JS files into the public folder

== Previewing the Theme Locally

The theme can be preview either on it's own or you can build against some of our documentation.

First, install the relevant Node scripts in the top level of the repo, in a terminal type:

`npm install`

=== Preview Theme Only

In the top level of this repo, in a terminal type:

`npx gulp preiew`

You should see some output in your terminal pointing you to a local address and port. Viewing this will shoe you the place-holder content types.

=== Preview Theme with Real Content

The resulting build does not includes a means to serve the content so for this you will need to run a small web server, it only needs to host HTML so nothing complicated is required. You can either use your own setup or alternatively clone the repo below that was created specifically for this purpose, see the readme in the server repo for how to use it.

* A Payara Documentation repo
* https://github.com/diturner/previewAntoraLocally[previewAntoraLocally]

Create the theme zip file we'll pull into a docs build. This will create a zip at `build/ui-bundle.zip`. In the top level of the theme repo type:

`npx gulp bundle`

From the top level of the documentation repo build the docs, this example uses the Cloud docs repo. I'm assuming here that both the theme and the docs repos are in the same folder:

`npx antora --fetch local-playbook.yml --ui-bundle-url "./../antora-ui-default/build/ui-bundle.zip"`

== Copyright and License

This code is based on the {url-project}[default Antora UI].

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

